### ISSUE TITLE
require.context in i18n does not play nicely

### ISSUE THREAD

**Issue by hitchcockwill** [udacity/create-ureact-app#11]
Implementations of `ureact-i18n` include `var i18n = new _ureactI18n.I18n(require.context('../locales'));` which does not play nicely with uCRA.

```
TypeError: require.context is not a function

      12 |       cardId: PropTypes.string
      13 |     })
    > 14 |   };
      15 |
      16 |   render() {
      17 |     if (_.isEmpty(this.props.existingData)) {

      at Object.<anonymous> (node_modules/@udacity/ureact-payment/build/services/localization-service.js:9:41)
      at Object.<anonymous> (node_modules/@udacity/ureact-payment/build/components/credit-card-form.js:39:28)
      at Object.<anonymous> (node_modules/@udacity/ureact-payment/build/index.js:3:23)
      at Object.<anonymous> (src/app/components/payment-methods/stripe.jsx:14:22)
      at Object.<anonymous> (src/app/components/payment-container.jsx:20:38)
      at Object.<anonymous> (src/app/views/checkout.jsx:20:48)
      at Object.<anonymous> (src/app/app.jsx:18:40)
      at Object.<anonymous> (src/app/app.spec.jsx:7:12)
```

require.context is not supported by CRA and probably won't be based on this discussion:
https://github.com/facebook/create-react-app/issues/517

**Comment by hitchcockwill** [comment]
With some slight tweaks to `ureact-i18n` I think we can skip using `require.context` altogether.

When we initialize `i18n` in our apps we can do this:

```js
const i18n = new I18n({
  'de.js': require('../locales/de.js')
});

// old
const i18n = new I18n(require.context('../locales'));
```

The downside is that we need to list each locale file but that seems like a small price to pay.

```js
// in ureact-i18n/src/i18n.js

function mapLocalesFromFiles(localeFileContext, oldLocales) {
  return _.chain(_.keys(localeFileContext)) // add lodash keys here
    .filter((filename) => /\.js$/.test(filename))
    .reduce((memo, filename) => {
      const name = getBasename(filename).toLowerCase();
      // const latestLocales = localeFileContext(filename) // was this before
const latestLocales = typeof localeFileContext === 'function' ? localeFileContext(filename) : localeFileContext[filename];
      memo[name] = _.isUndefined(oldLocales) || _.isUndefined(oldLocales[name])
        ? latestLocales
        : {
          ...oldLocales[name],
          ...latestLocales
        };
      return memo;
    }, oldLocales || {})
    .value();
}

```

**Comment by dcwither** [comment]
I think we should suggest the async path
```
'de': () => import('<de locale path>')
```

**Comment by hitchcockwill** [comment]
This should be resolved by: https://github.com/udacity/ureact-i18n/pull/35
